packages:
  - "packages/*"
publicHoistPattern:
  - eslint
  - prettier
allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  esbuild: true
  core-js: false
minimumReleaseAgeExclude:
  - tabler-animated@1.0.0
