import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

export const ROOT_PATH = path.resolve(path.resolve(), '../');

const CORE_ICONS_DIR = path.join(ROOT_PATH, 'core/src/icons');
const CORE_INDEX_FILE = path.join(ROOT_PATH, 'core/src/index.ts');
const CORE_IMPORT_PATH = 'tabler-animated';

const OUTPUT_DIR = path.join(ROOT_PATH, 'docs/generated');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'icons.tsx');

const EXPORT_LINE_REGEX = /export\s*{\s*(\w+)\s*}\s*from\s*'\.\/icons\/([\w-]+)'\s*;/g;

const getExportsByIconName = (indexSource: string) => {
  const exportsByIconName = new Map<string, string>();

  for (const [, componentName, iconName] of indexSource.matchAll(EXPORT_LINE_REGEX)) {
    exportsByIconName.set(iconName, componentName);
  }

  return exportsByIconName;
};

const getIconNames = () =>
  fs
    .readdirSync(CORE_ICONS_DIR)
    .filter((file) => file.endsWith('.tsx'))
    .map((file) => file.replace(/\.tsx$/, ''))
    .sort((a, b) => a.localeCompare(b));

const generateRegistry = () => {
  const indexSource = fs.readFileSync(CORE_INDEX_FILE, 'utf-8');
  const exportsByIconName = getExportsByIconName(indexSource);

  const icons = getIconNames().flatMap((name) => {
    const componentName = exportsByIconName.get(name);

    if (!componentName) {
      console.warn(`Skipping "${name}": no export for './icons/${name}' found in index.ts`);
      return [];
    }

    return [{ name, componentName }];
  });

  const importNames = icons.map((icon) => icon.componentName).join(', ');
  const entries = icons
    .map((icon) => `  { name: '${icon.name}', component: ${icon.componentName} }`)
    .join(',\n');

  const content = `// This file is auto-generated by scripts/generate-registry.ts. Do not edit manually.
import type { IconComponent } from '${CORE_IMPORT_PATH}/types';
import { ${importNames} } from '${CORE_IMPORT_PATH}';

export interface IconRegistryItem {
  name: string;
  component: IconComponent;
}

export const ICON_LIST: IconRegistryItem[] = [
${entries}
];
`;

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
  execSync(`pnpm prettier --write ${JSON.stringify(OUTPUT_FILE)}`, { cwd: ROOT_PATH });

  console.log(`Generated ${icons.length} icon(s) -> ${path.relative(ROOT_PATH, OUTPUT_FILE)}`);
};

generateRegistry();
